export const GET_A_PRODUCT_REQUEST = 'GET_A_PRODUCT_REQUEST'
export const GET_A_PRODUCT_SUCCESS = 'GET_A_PRODUCT_SUCCESS'
export const GET_A_PRODUCT_FAIL = 'GET_A_PRODUCT_FAIL'

export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL'